export const arr_stations=[
  {
    id:2852,
    city:'bnei-brak',
    street:'akiva',
    busLine:[7,9,5,53,164],
  },
  {
    id:3,
    city:'bnei-brak',
    street:'uizhel',
    busLine:[7,9,5,3],
  },
  {
    id:4,
    city:'elad',
    street:'yehuda-hanasi',
    busLine:[180,280,4],
  },
  { 
    id:5,
    city:'yerushlaim',
    street:'geula',
    busLine:[59,66,3,1],
  },
];  